#!/bin/bash
SCRIPTNAME=`basename $0`
SOURCE_LIST=(`find . -name type.[ch]`)
TYPE_LIST=(`grep 'CODEGEN' ${SOURCE_LIST[@]} | cut -d ' ' -f 3`)
BASEFILE=src/template.c
DIR=src/template
mkdir -p $DIR
echo "// Generated by $SCRIPTNAME" > $BASEFILE
echo "enum {COMMON_DEBUG=0};" >> $BASEFILE
for t in ${TYPE_LIST[@]}; do
  echo $t
  t=`basename $t S`
  FILE="$DIR/t_$t.c"
  echo "// Generated by $SCRIPTNAME" > $FILE
  ,template.sh "ARR_REUSE($t, 256);" >> $FILE
  echo "#include \"$FILE\"" >> $BASEFILE
done
clang-format -i $BASEFILE
