#!/bin/bash
SCRIPTNAME=`basename $0`
TYPE_LIST=("obj" "mon")
for t in ${TYPE_LIST[@]}; do
  echo $t
  FILE="src/game/t_$t.c"
  echo "// Generated by $SCRIPTNAME" > $FILE
  ,template.sh "ARR_REUSE($t, 256);" >> $FILE
done
