#include "game/common.h"
#include "game/table.h"
#include "game/type.h"
#include "game/var.h"
#include "game/xxap.h"
#include "game/xxcast.h"
#include "game/xxinline.h"

#include "local/const.c"
#include "local/macro.c"
#include "local/type.c"
#include "local/xvar.c"

#include "db/char.c"
#include "db/crown.c"
#include "db/desc.c"
#include "db/grave.c"
#include "db/mon.c"
#include "db/obj.c"

#include "src/pre.h"
#include "src/template.c"
