#include "game/common.h"
#include "game/const.h"
#include "game/type.h"
#include "game/var.h"
#include "game/xxinline.c"

#include "db/char.c"
#include "db/desc.c"
#include "db/grave.c"
#include "db/mon.c"
#include "db/obj.c"
