STATIC int FDECL(read_input, ());
STATIC int FDECL(replay_playback, ());
STATIC int FDECL(replay_recording, ());
STATIC int FDECL(replay_resumed, ());
STATIC char FDECL(game_input, ());
STATIC void FDECL(vital_update, ());
STATIC int FDECL(los, (int fromY, int fromX, int toY, int toX));
STATIC int FDECL(py_affect, (int maid));
STATIC int FDECL(py_tr, (int trflag));
STATIC int FDECL(uvow, (int idx));
STATIC int FDECL(py_speed, ());
STATIC int FDECL(think_adj, (int stat));
STATIC int FDECL(uspellcount, ());
STATIC int FDECL(uspellmask, ());
STATIC struct spellS* FDECL(uspelltable, ());
STATIC void FDECL(affect_update, ());
STATIC int FDECL(msg_advance, ());
STATIC void FDECL(replay_hack, ());
STATIC uint64_t FDECL(replay_hash, ());
STATIC void FDECL(replay_start, ());
STATIC void FDECL(replay_end, ());
STATIC int FDECL(in_bounds, (int row, int col));
STATIC int FDECL(viz_magick, ());
STATIC int FDECL(draw, (int wait));
STATIC void FDECL(msg_pause, ());
STATIC void FDECL(msg_hint, (char* hint, int hintlen));
STATIC void FDECL(msg_write, (char* msg, int msglen, int msg_width));
STATIC void FDECL(msg_game, (char* msg, int msglen, int msg_width));
STATIC int FDECL(show_history, ());
STATIC int FDECL(in_subcommand, (char* prompt, char* command));
STATIC char FDECL(map_roguedir, (int comval));
STATIC int FDECL(get_dir, (char* prompt, int* dir));
STATIC int FDECL(bit_pos, (uint32_t* test));
STATIC void FDECL(go_up, ());
STATIC void FDECL(go_down, ());
STATIC int FDECL(cave_floor_near, (int y, int x));
STATIC void FDECL(place_boundary, ());
STATIC int FDECL(rnd, ());
STATIC int FDECL(randint, (int maxval));
STATIC int FDECL(randnor, (int mean, int stand));
STATIC void FDECL(seed_init, (int prng));
STATIC int FDECL(fixed_seed_func, (int seed, fn func));
STATIC int FDECL(damroll, (int num, int sides));
STATIC int FDECL(pdamroll, (uint8_t* array));
STATIC int FDECL(critical_blow, (int weight, int plus, int lev_adj, int dam));
STATIC int FDECL(tot_dam, (struct objS * obj, int tdam, int cidx));
STATIC void FDECL(build_type1,
                  (int ychunk, int xchunk, int* ycenter, int* xcenter));
STATIC void FDECL(build_room,
                  (int ychunk, int xchunk, int* ycenter, int* xcenter));
STATIC void FDECL(build_store, (int sidx, int y, int x));
STATIC void FDECL(side_entrance, (int rv, int tchar));
STATIC int FDECL(near_light, (int y, int x));
STATIC int FDECL(build_bounds, (int row, int col));
STATIC int FDECL(diff_chunk, (int y1, int x1, int y2, int x2));
STATIC void FDECL(place_broken_door, (int broken, int y, int x));
STATIC void FDECL(place_closed_door, (int locked, int y, int x));
STATIC void FDECL(place_secret_door, (int y, int x));
STATIC void FDECL(place_door, (int y, int x));
STATIC int FDECL(same_chunk, (int y1, int x1, int y2, int x2));
STATIC point_t FDECL(protect_floor, (int y, int x, int ydir, int xdir));
STATIC point_t FDECL(find_perp_threshold,
                     (int row, int col, int row_dir, int col_dir));
STATIC int FDECL(bestdir, (int row1, int col1, int row2, int col2));
STATIC int FDECL(dirflag, (int row1, int col1, int row2, int col2));
STATIC int FDECL(build_diag, (int row1, int col1, int row2, int col2,
                              point_t* tunstk, int* tunindex));
STATIC void FDECL(perp_rc_dir,
                  (int tmp_row, int tmp_col, int* row_dir, int* col_dir));
STATIC void FDECL(build_corridor, (int row1, int col1, int row2, int col2));
STATIC void FDECL(granite_cave, ());
STATIC void FDECL(delete_object, (int y, int x));
STATIC char* FDECL(describe_use, (int iidx));
STATIC void FDECL(inven_destroy, (int iidx));
STATIC void FDECL(inven_destroy_num, (int iidx, int number));
STATIC int FDECL(inven_copy_num, (int iidx, struct objS* copy, int num));
STATIC void FDECL(place_stair_tval, (int y, int x, int tval));
STATIC void FDECL(new_spot, (int* y, int* x));
STATIC int FDECL(next_to_object, (int y1, int x1));
STATIC void FDECL(place_stairs, (int tval, int num));
STATIC int FDECL(num_adjacent_corridor, (int y, int x));
STATIC int FDECL(is_corridor, (int y, int x));
STATIC void FDECL(try_door, (int y, int x));
STATIC int FDECL(set_null, ());
STATIC int FDECL(check_fval_type, (int fval, int ftyp));
STATIC void FDECL(tr_obj_copy, (int tidx, struct objS* obj));
STATIC int FDECL(magik, (int chance));
STATIC int FDECL(m_bonus, (int base, int max_std, int level));
STATIC int FDECL(light_adj, (int p1));
STATIC int FDECL(ustackweight, ());
STATIC int FDECL(stacklimit_by_max_weight, (int max, int weight));
STATIC int FDECL(number_by_weight_roll, (int weight, int num, int sides));
STATIC void FDECL(magic_treasure, (struct objS * obj, int level));
STATIC int FDECL(mask_subval, (int sv));
STATIC int FDECL(knowable_tval_subval, (int tval, int sv));
STATIC void FDECL(tr_unknown_sample,
                  (struct treasureS * tr_ptr, int* unknown, char** sample));
STATIC int FDECL(tr_is_known, (struct treasureS * tr_ptr));
STATIC void FDECL(tr_discovery, (struct treasureS * tr_ptr));
STATIC int FDECL(tr_make_known, (struct treasureS * tr_ptr));
STATIC void FDECL(tr_sample, (struct treasureS * tr_ptr));
STATIC int FDECL(vuln_fire, (struct objS * obj));
STATIC int FDECL(vuln_fire_breath, (struct objS * obj));
STATIC int FDECL(vuln_acid, (struct objS * obj));
STATIC int FDECL(vuln_acid_breath, (struct objS * obj));
STATIC int FDECL(vuln_frost, (struct objS * obj));
STATIC int FDECL(vuln_lightning, (struct objS * obj));
STATIC int FDECL(vuln_gas, (struct objS * obj));
STATIC int FDECL(is_door, (int tval));
STATIC int FDECL(crset_evil, (struct creatureS * cre));
STATIC int FDECL(crset_visible, (struct creatureS * cre));
STATIC int FDECL(crset_invisible, (struct creatureS * cre));
STATIC int FDECL(oset_sightfm, (struct objS * obj));
STATIC int FDECL(oset_mon_pickup, (struct objS * obj));
STATIC int FDECL(oset_pickup, (struct objS * obj));
STATIC int FDECL(mpickup_obj, (struct objS * obj));
STATIC int FDECL(oset_trap, (struct objS * obj));
STATIC int FDECL(oset_doorstair, (struct objS * obj));
STATIC int FDECL(oset_hidden, (struct objS * obj));
STATIC int FDECL(oset_zap, (struct objS * obj));
STATIC int FDECL(oset_weightcheck, (struct objS * obj));
STATIC int FDECL(oset_tohitdam, (struct objS * obj));
STATIC int FDECL(oset_equip, (struct objS * obj));
STATIC int FDECL(oset_enchant, (struct objS * obj));
STATIC int FDECL(oset_rare, (struct objS * obj));
STATIC int FDECL(oset_melee, (struct objS * obj));
STATIC int FDECL(oset_dice, (struct objS * obj));
STATIC int FDECL(oset_dammult, (struct objS * obj));
STATIC int FDECL(oset_armor, (struct objS * obj));
STATIC int FDECL(oset_gold, (struct objS * obj));
STATIC int FDECL(oset_obj, (struct objS * obj));
STATIC int FDECL(set_large, (struct treasureS * item));
STATIC int FDECL(may_equip, (int tval));
STATIC int FDECL(may_enchant_ac, (int tval));
STATIC int FDECL(ring_slot, ());
STATIC void FDECL(store_init, ());
STATIC int FDECL(store_item_destroy, (int sidx, int item, int count));
STATIC int FDECL(store_tr_stack, (int sidx, int tr_index, int stack));
STATIC void FDECL(store_sort, (int sidx));
STATIC void FDECL(store_maint, ());
STATIC void FDECL(map_area, ());
STATIC int FDECL(get_obj_num, (int level, int must_be_small));
STATIC int FDECL(get_mon_num, (int level));
STATIC int FDECL(place_monster, (int y, int x, int z, int slp));
STATIC int FDECL(place_win_monster, ());
STATIC int FDECL(summon_monster, (int y, int x));
STATIC int FDECL(summon_undead, (int y, int x));
STATIC void FDECL(alloc_townmon, (int num));
STATIC void FDECL(alloc_mon, (int num, int dis, int slp));
STATIC void FDECL(place_rubble, (int y, int x));
STATIC void FDECL(place_gold, (int y, int x));
STATIC int FDECL(place_object, (int y, int x, int must_be_small));
STATIC int FDECL(place_trap, (int y, int x, int offset));
STATIC void FDECL(alloc_obj, (int ftyp, int otyp, int num));
STATIC void FDECL(build_vault, (int y, int x));
STATIC void FDECL(build_pillar, (int y, int x));
STATIC void FDECL(build_chamber, (int y, int x, int h, int w));
STATIC int FDECL(chunk_obj, (int ychunk, int xchunk, int obj_count, fn func));
STATIC void FDECL(room_monster, (int y, int x, int chance));
STATIC void FDECL(fill_rectangle, (int xmin, int xmax, int ymin, int ymax,
                                   int rflag, int floor, fn setup_func));
STATIC int FDECL(checkered_setup,
                 (struct caveS * c_ptr, int i, int j, int floor));
STATIC int FDECL(quadrant_setup,
                 (struct caveS * c_ptr, int i, int j, int floor));
STATIC int FDECL(preserve_setup,
                 (struct caveS * c_ptr, int i, int j, int floor));
STATIC void FDECL(build_type2, (int ychunk, int xchunk, int* ycenter,
                                int* xcenter, int type1, int type2));
STATIC int FDECL(mmove, (int dir, int* y, int* x));
STATIC void FDECL(place_streamer, (int fval, int treas_chance));
STATIC int FDECL(cave_gen, ());
STATIC int FDECL(town_night, ());
STATIC int FDECL(town_gen, ());
STATIC int FDECL(py_intown, ());
STATIC int FDECL(hard_reset, ());
STATIC void FDECL(panel_bounds, (struct panelS * panel));
STATIC void FDECL(panel_update,
                  (struct panelS * panel, int y, int x, int force));
STATIC void FDECL(get_moves, (int midx, int* mm));
STATIC int FDECL(see_wall, (int dir, int y, int x));
STATIC void FDECL(find_init, (int dir, int* y_ptr, int* x_ptr));
STATIC int FDECL(see_nothing, (int dir, int y, int x));
STATIC int FDECL(find_event, (int y, int x));
STATIC int FDECL(detect_obj, (int (*valid)(), int known));
STATIC int FDECL(detect_by_mflag, (int mflag, int cridx));
STATIC int FDECL(detect_mon, (int ma_type, int known));
STATIC void FDECL(move_rec, (int y1, int x1, int y2, int x2));
STATIC int FDECL(perceive_creature, (struct creatureS * cr_ptr));
STATIC int FDECL(perceive_creature2, (struct creatureS * cr_ptr));
STATIC int FDECL(mon_lit, (int midx));
STATIC int FDECL(mon_multiply, (struct monS * mon));
STATIC void FDECL(light_room, (int y, int x));
STATIC int FDECL(illuminate, (int y, int x));
STATIC void FDECL(unlight_room, (int y, int x));
STATIC int FDECL(unlight_area, (int y, int x));
STATIC void FDECL(py_light_off, (int y, int x));
STATIC void FDECL(py_light_on, (int y, int x));
STATIC void FDECL(py_check_view, ());
STATIC int FDECL(enchant, (int16_t* bonus, int16_t limit));
STATIC int FDECL(tohit_by_weight, (int weight));
STATIC int FDECL(attack_blows, (int weight));
STATIC int FDECL(bth_adj, (int attype));
STATIC char* FDECL(attack_string, (int adesc));
STATIC int FDECL(sustain_stat, (int sidx));
STATIC int FDECL(con_adj, ());
STATIC int FDECL(chr_adj, ());
STATIC int FDECL(poison_adj, ());
STATIC int FDECL(tohit_adj, ());
STATIC int FDECL(toac_adj, ());
STATIC int FDECL(todis_adj, ());
STATIC int FDECL(todam_adj, ());
STATIC int FDECL(umana_by_level, (int level));
STATIC int FDECL(usave, ());
STATIC int FDECL(udevice, ());
STATIC int FDECL(udisarm, ());
STATIC int FDECL(gain_prayer, ());
STATIC int FDECL(test_hit, (int bth, int level_adj, int pth, int ac));
STATIC int FDECL(is_a_vowel, (int chr));
STATIC int FDECL(moriap_fmt_obj,
                 (char* fmt, int flen, int fflag, struct objS* obj));
STATIC int FDECL(obj_detail, (struct objS * obj, int fmt));
STATIC int64_t FDECL(moria_ocat_num,
                     (char* dst, int dstlen, char* objname, int num));
STATIC int FDECL(moriap_bonus, (char* dst, int dstlen, int p1));
STATIC char* FDECL(store_name, (int tchar));
STATIC void FDECL(obj_desc, (struct objS * obj, int number));
STATIC int FDECL(mon_desc, (int midx));
STATIC void FDECL(death_desc, (char* special));
STATIC void FDECL(death_obj, (struct objS * obj));
STATIC char* FDECL(death_text, ());
STATIC int FDECL(summon_object, (int y, int x, int num, int typ));
STATIC void FDECL(memory_of_kill, (int cidx, int ogcount));
STATIC int FDECL(mon_death, (int y, int x, int flags));
STATIC int FDECL(mon_take_hit, (int midx, int dam));
STATIC void FDECL(calc_hitpoints, ());
STATIC void FDECL(calc_mana, ());
STATIC void FDECL(calc_bonuses, ());
STATIC void FDECL(ma_bonuses, (int maffect, int factor));
STATIC void FDECL(add_ma_count, (int maidx, int count));
STATIC void FDECL(ma_duration, (int maidx, int nturn));
STATIC void FDECL(ma_combat, (int maidx, int nturn));
STATIC int FDECL(ma_clear, (int maidx));
STATIC int8_t FDECL(modify_stat, (int tmp_stat, int amount));
STATIC void FDECL(set_use_stat, (int stat));
STATIC void FDECL(py_bonuses, (struct objS * obj, int factor));
STATIC int FDECL(equip_swap_into, (int iidx, int into_slot));
STATIC void FDECL(inven_drop, (int iidx));
STATIC int FDECL(player_saves, ());
STATIC int FDECL(equip_vibrate, (int flag));
STATIC int FDECL(equip_random, ());
STATIC int FDECL(equip_enchant, (int iidx, int amount));
STATIC int FDECL(equip_curse, ());
STATIC int FDECL(equip_remove_curse, ());
STATIC int FDECL(equip_disenchant, ());
STATIC int FDECL(inven_random, ());
STATIC int FDECL(inven_slot, ());
STATIC void FDECL(inven_used_obj, (struct objS * obj));
STATIC int FDECL(inven_obj_mergecount, (struct objS * obj, int number));
STATIC int FDECL(inven_food, ());
STATIC int FDECL(inven_ident, (int iidx));
STATIC int FDECL(weapon_enchant, (int iidx, int tohit, int todam));
STATIC int FDECL(make_special_type, (int iidx, int lev, int weapon_enchant));
STATIC int FDECL(rest_affect, ());
STATIC void FDECL(py_rest, ());
STATIC int FDECL(py_take_hit, (int damage));
STATIC void FDECL(py_stats, (int8_t* stats, int len));
STATIC int FDECL(heroname_init, ());
STATIC int FDECL(social_bonus, ());
STATIC int FDECL(value_by_stat, (int stat));
STATIC void FDECL(py_gold_init, ());
STATIC int FDECL(clamp, (int val, int min, int max));
STATIC void FDECL(py_race_class_seed_init, (int rsel, int csel, int prng));
STATIC void FDECL(py_inven_init, ());
STATIC void FDECL(sort, (void* array, int len));
STATIC int FDECL(magic_init, ());
STATIC int FDECL(dec_stat, (int stat));
STATIC int FDECL(inc_stat, (int stat));
STATIC void FDECL(lose_stat, (int sidx));
STATIC int FDECL(res_stat, (int stat));
STATIC int FDECL(low_stat, ());
STATIC void FDECL(py_where_on_map, ());
STATIC void FDECL(py_add_food, (int num));
STATIC int FDECL(py_heal_hit, (int num));
STATIC int FDECL(py_expmult, ());
STATIC int FDECL(lev_exp, (int lev));
STATIC int FDECL(expmult_update, ());
STATIC void FDECL(py_experience, ());
STATIC int FDECL(restore_level, ());
STATIC int FDECL(py_lose_experience, (int amount));
STATIC void FDECL(teleport_to, (int ny, int nx));
STATIC void FDECL(py_teleport, (int dis, int* uy, int* ux));
STATIC void FDECL(teleport_away, (int midx, int dis));
STATIC int FDECL(is_obj_vulnmelee, (struct objS * obj, int vulnmelee));
STATIC int FDECL(is_obj_vulntype, (struct objS * obj, int vulntyp));
STATIC void FDECL(get_flags, (int typ, uint32_t* weapon_type, int* harm_type));
STATIC void FDECL(light_line, (int dir, int y, int x));
STATIC void FDECL(magic_bolt,
                  (int typ, int dir, int y, int x, int dam, char* bolt_typ));
STATIC void FDECL(fire_ball,
                  (int typ, int dir, int y, int x, int dam_hp, char* descrip));
STATIC int FDECL(twall, (int y, int x));
STATIC int FDECL(wall_to_mud, (int dir, int y, int x));
STATIC int FDECL(poly_monster, (int dir, int y, int x));
STATIC int FDECL(hp_monster, (int dir, int y, int x, int dam));
STATIC int FDECL(confuse_monster, (int dir, int y, int x));
STATIC int FDECL(sleep_monster, (int dir, int y, int x));
STATIC int FDECL(sleep_monster_aoe, (int maxdis));
STATIC int FDECL(mass_poly, ());
STATIC int FDECL(drain_life, (int dir, int y, int x));
STATIC int FDECL(td_destroy_bolt, (int dir, int y, int x));
STATIC int FDECL(build_wall, (int dir, int y, int x));
STATIC int FDECL(clone_monster, (int dir, int y, int x));
STATIC int FDECL(teleport_monster, (int dir, int y, int x));
STATIC int FDECL(disarm_all, (int dir, int y, int x));
STATIC int FDECL(dispel_creature, (int cflag, int damage));
STATIC int FDECL(genocide, (int cidx));
STATIC int FDECL(mass_genocide, (int y, int x));
STATIC int FDECL(inven_recharge, (int iidx, int rigor));
STATIC int FDECL(sleep_adjacent, (int y, int x));
STATIC int FDECL(swap_2i, (int* left, int* right));
STATIC int FDECL(create_food, (int y, int x, int known));
STATIC int FDECL(turn_undead, ());
STATIC void FDECL(warding_glyph, (int y, int x));
STATIC int FDECL(trap_creation, (int y, int x));
STATIC int FDECL(td_destroy, (int y, int x));
STATIC int FDECL(aggravate_monster, (int dis_affect));
STATIC int FDECL(door_creation, ());
STATIC int FDECL(speed_monster_aoe, (int spd));
STATIC int FDECL(speed_monster, (int dir, int y, int x, int spd));
STATIC void FDECL(replace_spot, (int y, int x, int typ));
STATIC void FDECL(earthquake, ());
STATIC void FDECL(destroy_area, (int y, int x));
STATIC void FDECL(starlite, (int y, int x));
STATIC int FDECL(obj_cmp, (struct objS * a, struct objS* b));
STATIC int FDECL(inven_sort, ());
STATIC int FDECL(inven_reveal, ());
STATIC int FDECL(inven_overlay, (int begin, int end, int show_weight));
STATIC int FDECL(weapon_curse, ());
STATIC int FDECL(inven_eat, (int iidx));
STATIC int FDECL(obj_tabil, (struct objS * obj, int truth));
STATIC int FDECL(obj_tbonus, (struct objS * obj));
STATIC int FDECL(strip_tail, (int line));
STATIC int FDECL(screen_scry_obj, (int sflag, struct objS* obj));
STATIC int FDECL(obj_study, (struct objS * obj, int town_store));
STATIC int FDECL(inven_choice, (char* prompt, char* mode_list));
STATIC int FDECL(inven_quaff, (int iidx));
STATIC int FDECL(inven_read, (int iidx, int* uy, int* ux));
STATIC int FDECL(inven_try_wand_dir, (int iidx, int dir));
STATIC void FDECL(py_zap, (int iidx));
STATIC int FDECL(gain_spell, (int spidx));
STATIC int FDECL(spell_prompt, (int spidx, int low_mana));
STATIC void FDECL(spell_dir_target,
                  (int spidx, int* y_ptr, int* x_ptr, int target));
STATIC int FDECL(book_prompt, (char** names, struct spellS* spelltable,
                               int spmask, uint32_t bookflags));
STATIC void FDECL(py_magic, (int iidx, int* y_ptr, int* x_ptr));
STATIC int FDECL(prayer_prompt, (int pridx, int low_mana));
STATIC int FDECL(prayer_dir_target,
                 (int pridx, int* y_ptr, int* x_ptr, int dir));
STATIC void FDECL(py_prayer, (int iidx, int* y_ptr, int* x_ptr));
STATIC int FDECL(inven_try_staff, (int iidx, int* uy, int* ux));
STATIC int FDECL(inven_flask, (int iidx));
STATIC int FDECL(inven_merge, (int obj_id, int* locn));
STATIC int FDECL(weight_limit, ());
STATIC void FDECL(inven_check_weight, ());
STATIC int FDECL(inven_consume_flask, ());
STATIC void FDECL(inven_check_light, ());
STATIC int FDECL(inven_carry, (int obj_id));
STATIC int FDECL(obj_sense, (struct objS * obj));
STATIC int FDECL(obj_rare, (struct objS * obj));
STATIC int FDECL(obj_magik, (struct objS * obj));
STATIC void FDECL(inven_wear, (int iidx));
STATIC int FDECL(bow_by_projectile, (int pidx));
STATIC int FDECL(obj_dupe_num, (struct objS * obj, int num));
STATIC int FDECL(obj_thrown, (struct objS * obj, int y, int x));
STATIC int FDECL(mon_surprise, (struct monS * m_ptr, int mlit));
STATIC void FDECL(inven_throw_dir, (int iidx, int dir));
STATIC void FDECL(py_throw, (int iidx));
STATIC void FDECL(py_offhand, ());
STATIC int FDECL(door_try_close, (int y, int x));
STATIC int FDECL(door_try_jam, (int y, int x));
STATIC int FDECL(try_spike_dir, (int dir));
STATIC void FDECL(py_spike, (int iidx));
STATIC int FDECL(show_version, ());
STATIC char* FDECL(usex, ());
STATIC int FDECL(show_character, ());
STATIC int FDECL(saveslot_validation, ());
STATIC void FDECL(summary_update, (struct summaryS * summary));
STATIC int FDECL(py_archive_read, (struct summaryS * summary, int external));
STATIC int FDECL(summary_saveslot_deletion,
                 (struct summaryS * summary, int saveslot, int external));
STATIC int FDECL(saveslot_race_reroll, (int saveslot, int race));
STATIC int FDECL(saveslot_creation, (int saveslot));
STATIC int FDECL(py_notes_menu, ());
STATIC int FDECL(py_saveslot_select, ());
STATIC int FDECL(py_king, ());
STATIC int FDECL(py_grave, ());
STATIC int FDECL(can_undo, (int offset));
STATIC int FDECL(can_reset, (int death));
STATIC void FDECL(py_undo, ());
STATIC void FDECL(dungeon_reset, (int death));
STATIC int FDECL(py_help, ());
STATIC int FDECL(py_menu, ());
STATIC int FDECL(py_teleport_near, (int y, int x, int* uy, int* ux));
STATIC int FDECL(wizard_prompt, (int* yptr, int* xptr));
STATIC int FDECL(confirm_transition, (int prev, char* trans));
STATIC int FDECL(py_endgame, (fn endtype));
STATIC int FDECL(inven_damage, (int typ, int perc));
STATIC int FDECL(minus_ac, (int verbose));
STATIC int FDECL(poison_gas, (int dam));
STATIC int FDECL(fire_dam, (int dam));
STATIC int FDECL(acid_dam, (int dam, int verbose));
STATIC int FDECL(frost_dam, (int dam));
STATIC int FDECL(light_dam, (int dam));
STATIC void FDECL(corrode_gas, (int verbose));
STATIC void FDECL(py_attack, (int y, int x));
STATIC void FDECL(mon_attack, (int midx));
STATIC void FDECL(chest_trap, (int y, int x));
STATIC void FDECL(try_disarm_trap, (int y, int x));
STATIC void FDECL(try_disarm_chest, (int y, int x));
STATIC void FDECL(door_bash, (int y, int x));
STATIC void FDECL(py_drop, ());
STATIC void FDECL(open_object, (int y, int x));
STATIC void FDECL(py_search, (int y, int x));
STATIC void FDECL(py_pickup, (int y, int x, int pickup));
STATIC int FDECL(py_monlook_dir, (int dir));
STATIC int FDECL(py_objlook_dir, (int dir));
STATIC void FDECL(py_examine, ());
STATIC int FDECL(mon_bestiary, (struct monS * mon, struct creatureS* cre));
STATIC void FDECL(mon_look, (int midx));
STATIC void FDECL(py_look, (int y, int x));
STATIC int FDECL(objdig_wall_plus,
                 (struct objS * obj, int wall_chance, int wall_min));
STATIC int FDECL(tunnel_tool, (int y, int x, int iidx));
STATIC int FDECL(tunnel, (int y, int x));
STATIC void FDECL(py_tunnel, (int iidx));
STATIC void FDECL(make_move, (int midx, int* mm, uint32_t* rc_ptr));
STATIC void FDECL(mon_breath_msg, (int breath));
STATIC void FDECL(mon_breath_dam,
                  (int midx, int fy, int fx, int breath, int breath_maxdam));
STATIC void FDECL(mon_try_multiply, (struct monS * mon));
STATIC int FDECL(mon_try_spell, (int midx, int cdis));
STATIC int FDECL(mon_move, (int midx));
STATIC int FDECL(movement_rate, (int speed));
STATIC int FDECL(creature_movement, (int* l_act));
STATIC int FDECL(creature_threat, (int* l_act));
STATIC int FDECL(creatures, ());
STATIC void FDECL(hit_trap, (int y, int x, int* uy, int* ux));
STATIC int FDECL(obj_value, (struct objS * obj));
STATIC int FDECL(store_value, (int sidx, int obj_value, int pawn));
STATIC int FDECL(obj_store_index, (struct objS * obj));
STATIC void FDECL(inven_pawn, (int iidx));
STATIC void FDECL(pawn_display, ());
STATIC void FDECL(store_display, (int sidx));
STATIC void FDECL(store_item_purchase, (int sidx, int item));
STATIC void FDECL(pawn_entrance, ());
STATIC void FDECL(stat_display, ());
STATIC void FDECL(stat_entrance, ());
STATIC void FDECL(vow_display, ());
STATIC void FDECL(vow_entrance, ());
STATIC void FDECL(store_entrance, (int sidx));
STATIC void FDECL(town_entrance, (int tval));
STATIC void FDECL(yx_autoinven, (int* y_ptr, int* x_ptr, int iidx));
STATIC void FDECL(py_reactuate, (int* y_ptr, int* x_ptr, int obj_id));
STATIC void FDECL(py_actuate, (int* y_ptr, int* x_ptr, int submode));
STATIC void FDECL(regenhp, (int percent));
STATIC void FDECL(regenmana, (int percent));
STATIC void FDECL(player_maint, ());
STATIC void FDECL(ma_tick, ());
STATIC void FDECL(tick, ());
STATIC int FDECL(dir_by_confusion, ());
STATIC void FDECL(fail, (char* text));
STATIC void FDECL(dungeon, ());
STATIC void FDECL(mon_level_init, ());
STATIC void FDECL(obj_level_init, ());
STATIC int FDECL(ftable_clear, (void* ftable, int size));
STATIC int FDECL(global_init, (int argc, char** argv));
