// Rufe.org LLC 2022-2024: ISC License
// TBD: user configuration?
// generated by lum_white.c: 7, 14, 21, 30
DATA int lightingD[] = {
    0xff151515,
    0xff252525,
    0xff393939,
    0xff4f4f4f,
};
// lum_white.c: 94
DATA int whiteD = 0xffededed;
// lum_color.c: LR 32, palette 7, odd indexes
DATA int color_mapD[] = {
    0xff1b0396, 0xff00539a, 0xff0299a1, 0xff109c04, 0xff8a9c02, 0xffa55907,
    0xff9e036d, 0xff62049b, 0xff5f65f2, 0xff509df2, 0xff5fe5f3, 0xff68f079,
    0xffdbf078, 0xfff19d6e, 0xffed5dbc, 0xffb06af4,
};

STATIC int
rgba_by_palette(c)
{
  return color_mapD[c];
}
#define font_rgba rgba_by_palette

#define COLOR 1
